### ISSUE TITLE
Sending introspection query 401 error

### ISSUE THREAD

**Issue by idkjs** [teberl/rag#1]
Thanks for sharing this.

I'm trying to get this introspection query to go.

github token settings are `reason-scopes — read:gpg_key, read:org, read:public_key, read:repo_hook, repo, user` 

```private/Token.re
let github = "5f9281ac13c***fsometoken**3daa6644c88857";
```
In package.json:

```json
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "prepare": "npm link bs-platform",
    "get-schema": "yarn send-introspection-query https://api.github.com/graphql --headers 'Authorization: bearer TOKEN'"
  },
```

Running `yarn get-schema` returns:
```s
$ /Users/prisc_000/Downloads/rag-master/node_modules/.bin/send-introspection-query https://api.github.com/graphql --headers 'Authorization: bearer TOKEN'
Non-ok status code from API:  401 Unauthorized```

What am i missing here? Thank you!

**Comment by teberl** [comment]
Hey @idkjs,

please notice that you cannot access the TOKEN from within your package.json.
The `Token.re` is only used for client code, so we don't have to copy/paste/replace the token value in the `Apollo.re:9`.

Please try to run in your terminal manually (i guess manually at setup is ok since you will not do this on regular basis)

`yarn send-introspection-query https://api.github.com/graphql --headers 'Authorization: bearer 5f9281ac13c***fsometoken**3daa6644c88857'`

The scopes are not needed for the __schema information.  Even with token without any scopes selected you are able to receive this information.

I hope this works for you, if so please let me know and i will update the READ.ME in order to make this step more clear.
